name: DriversF3

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  workflow_dispatch:
  schedule:
        # Practice session 
    - cron: '40 8 * * 5'

    # Qualifying session
    - cron: '35 13 * * 5'
    
    # Sprint race
    - cron: '20 9 * * 6'
    # Sprint race
    - cron: '20 8 * * 0'
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt
          playwright install --with-deps

      - name: Run scraper
        run: python f3.py
